# Generated by Django 3.2.5 on 2021-07-22 11:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pic/')),
                ('text', models.TextField(default='Poojitha Ravuri')),
                ('msg', ckeditor.fields.RichTextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='certis/')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='edu/')),
                ('clgname', models.CharField(max_length=1000)),
                ('degree', models.CharField(max_length=100)),
                ('years', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Poojitha')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='project name', max_length=100)),
                ('image', models.ImageField(upload_to='projects/')),
                ('msg', ckeditor.fields.RichTextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=2000)),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
            ],
        ),
    ]
