# Generated by Django 3.2.5 on 2021-07-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0002_delete_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='edu/')),
                ('clgname', models.CharField(max_length=1000)),
                ('degree', models.CharField(max_length=100)),
                ('years', models.CharField(max_length=100)),
            ],
        ),
    ]
